// Creates an isolated, randomly named database; never writes to the configured production database.
const path=require('path');
require('dotenv').config({path:path.join(__dirname,'../.env'),quiet:true});
const mysql=require('mysql2/promise');
const fs=require('fs/promises');
const assert=require('node:assert/strict');
const crypto=require('crypto');
const jwt=require('jsonwebtoken');
const bcrypt=require('bcrypt');
const dbName='hotel_test_'+crypto.randomBytes(8).toString('hex');
let control,pool,server,created=false;
const fileKeys=[];
async function main(){
 control=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,multipleStatements:true});
 const schema=await fs.readFile(path.join(__dirname,'../test/schema.sql'),'utf8');
 await control.query(schema.replace(/\bhotel_management\b/g,dbName));created=true;
 const seed=await fs.readFile(path.join(__dirname,'../test/seed.sql'),'utf8');await control.query(seed.replace(/\bhotel_management\b/g,dbName));
 process.env.DB_NAME=dbName;
 pool=require('../src/config/db');
 const h=require('../src/lib/hotel');
 const passwordHash=await bcrypt.hash('IntegrationTest123!',4);
 await pool.execute("INSERT INTO users (user_id,username,email,password_hash,role) VALUES (1,'testadmin','admin@example.com',?,'admin'),(2,'testcustomer','customer@example.com',?,'customer'),(3,'othercustomer','other@example.com',?,'customer')",[passwordHash,passwordHash,passwordHash]);
 await pool.execute("INSERT INTO customers (customer_id,user_id,first_name,last_name,phone) VALUES (1,2,'ทดสอบ','ลูกค้า','0800000000'),(2,3,'Other','Customer','0800000001')");
 let sentMail;
 process.env.SMTP_HOST='test.invalid';process.env.MAIL_FROM='test@example.com';process.env.PASSWORD_RESET_URL='http://localhost:5173/reset-password';
 require('nodemailer').createTransport=()=>({sendMail:async message=>{sentMail=message;}});
 server=require('../src/app').listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 const base='http://127.0.0.1:'+server.address().port+'/api';
 const sign=id=>jwt.sign({},process.env.JWT_SECRET,{subject:String(id),issuer:'hotel-management-api',audience:'hotel-management-web',expiresIn:'1h'});
 const admin=sign(1),customer=sign(2),other=sign(3);
 const request=async(route,method='GET',body,token=customer)=>{
  const response=await fetch(base+route,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const json=await response.json();return {status:response.status,body:json};
 };
 const ok=(r,status=200)=>{assert.equal(r.status,status,JSON.stringify(r.body));return r.body.data;};
 const today=h.today();const tomorrow=new Date(Date.parse(today)+86400000).toISOString().slice(0,10);
 ok(await request('/health','GET',undefined,null));
 ok(await request(`/rooms/availability?check_in=${today}&check_out=${tomorrow}&adults=2&children=0`,'GET',undefined,null));
 ok(await request('/room-types','GET',undefined,null));
 const bookingBody={check_in_date:today,check_out_date:tomorrow,rooms:[{room_id:1,adult_count:2,child_count:0}]};
 const duplicate=await Promise.all([request('/bookings','POST',bookingBody),request('/bookings','POST',bookingBody)]);
 assert.deepEqual(duplicate.map(r=>r.status).sort(),[201,409]);
 const booking=duplicate.find(r=>r.status===201).body.data;
 console.log('PASS concurrent booking: one success, one conflict');
 assert.equal((await request('/bookings/'+booking.booking_id,'GET',undefined,other)).status,403);
 assert.equal((await request('/admin/bookings')).status,403);
 ok(await request('/me/bookings'));ok(await request('/admin/bookings','GET',undefined,admin));
 const availability=ok(await request(`/rooms/availability?check_in=${today}&check_out=${tomorrow}&adults=2&children=0`));
 assert.ok(!availability.some(r=>r.room_id===1));
 assert.equal((await request('/admin/rooms/1','PATCH',{room_status:'maintenance'},admin)).status,409);
 const invalid=await request('/bookings','POST',{...bookingBody,rooms:[{room_id:2,adult_count:99}]});assert.equal(invalid.status,400);
 const cash=ok(await request(`/bookings/${booking.booking_id}/payments`,'POST',{amount:'900.00',payment_method:'cash'},admin),201);
 assert.equal((await request(`/bookings/${booking.booking_id}/payments`,'POST',{amount:'1.00',payment_method:'cash'},admin)).status,409);
 const verified=ok(await request(`/admin/payments/${cash.payment_id}/verify`,'PATCH',{status:'successful'},admin));
 assert.equal((await request(`/admin/payments/${cash.payment_id}/verify`,'PATCH',{status:'successful'},admin)).status,409);
 const receiptResponse=await fetch(base+`/receipts/${verified.receipt_id}/pdf`,{headers:{Authorization:'Bearer '+customer}});
 assert.equal(receiptResponse.status,200);const pdf=Buffer.from(await receiptResponse.arrayBuffer());assert.equal(pdf.subarray(0,5).toString(),'%PDF-');
 await fs.writeFile(path.join(__dirname,'../test/receipt-preview.pdf'),pdf);
 console.log('PASS payment verification and PDF receipt');
 const beforeDoc=await request(`/admin/bookings/${booking.booking_id}/check-in`,'POST',{},admin);assert.equal(beforeDoc.status,409);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jX1sAAAAASUVORK5CYII=','base64');
 const form=new FormData();form.set('document_type','national_id');form.set('file',new Blob([png],{type:'image/png'}),'test.png');
 const documentResponse=await fetch(base+`/bookings/${booking.booking_id}/identity-documents`,{method:'POST',headers:{Authorization:'Bearer '+customer},body:form});
 assert.equal(documentResponse.status,201);const doc=(await documentResponse.json()).data;
 const [[record]]=await pool.execute('SELECT file_path FROM identity_documents WHERE document_id=?',[doc.document_id]);fileKeys.push(record.file_path);
 assert.equal((await fetch(base+`/identity-documents/${doc.document_id}/file`,{headers:{Authorization:'Bearer '+other}})).status,403);
 ok(await request(`/admin/identity-documents/${doc.document_id}/review`,'PATCH',{status:'approved'},admin));
 const stay=ok(await request(`/admin/bookings/${booking.booking_id}/check-in`,'POST',{},admin),201);
 assert.equal((await request(`/admin/bookings/${booking.booking_id}/check-in`,'POST',{},admin)).status,409);
 ok(await request(`/admin/stays/${stay.stay_id}/additional-charges`,'POST',{charge_name:'Water',unit_price:'50.00',quantity:1},admin),201);
 assert.equal((await request(`/admin/bookings/${booking.booking_id}/check-out`,'POST',{},admin)).status,409);
 const additional=ok(await request(`/bookings/${booking.booking_id}/payments`,'POST',{amount:'50.00',payment_method:'cash'},admin),201);
 const additionalReceipt=ok(await request(`/admin/payments/${additional.payment_id}/verify`,'PATCH',{status:'successful'},admin));
 const [[rc]]=await pool.execute('SELECT room_amount,additional_amount FROM receipts WHERE receipt_id=?',[additionalReceipt.receipt_id]);
 assert.equal(rc.room_amount,'0.00');assert.equal(rc.additional_amount,'50.00');
 ok(await request(`/admin/bookings/${booking.booking_id}/check-out`,'POST',{},admin));
 const detail=ok(await request('/bookings/'+booking.booking_id));assert.equal(detail.financial.balance,'0.00');assert.equal(detail.booking_status,'checked_out');
 console.log('PASS identity access, check-in/out and additional-charge balance');
 const refundable=ok(await request('/bookings','POST',{...bookingBody,rooms:[{room_id:2,adult_count:1}]}),201);
 const rp=ok(await request(`/bookings/${refundable.booking_id}/payments`,'POST',{amount:'900.00',payment_method:'cash'},admin),201);
 ok(await request(`/admin/payments/${rp.payment_id}/verify`,'PATCH',{status:'successful'},admin));
 assert.equal((await request(`/bookings/${refundable.booking_id}/cancel`,'PATCH',{reason:'Test'})).status,409);
 ok(await request(`/admin/payments/${rp.payment_id}/refund`,'PATCH',{note:'Test refund recorded'},admin));
 ok(await request(`/bookings/${refundable.booking_id}/cancel`,'PATCH',{reason:'Test'}));
 ok(await request('/admin/dashboard','GET',undefined,admin));
 const report=ok(await request(`/admin/reports/cash-flow?from=${today}&to=${today}`,'GET',undefined,admin));assert.equal(report[0].net_cash_flow,'950.00');
 console.log('PASS refund/cancel, dashboard and cash-flow totals');
 const expired=ok(await request('/bookings','POST',{...bookingBody,rooms:[{room_id:3,adult_count:1}]}),201);
 await pool.execute('UPDATE bookings SET expires_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE booking_id=?',[expired.booking_id]);
 await h.expire();const expiredDetail=ok(await request('/bookings/'+expired.booking_id));assert.equal(expiredDetail.booking_status,'expired');
 console.log('PASS expired holds release rooms');
 ok(await request('/auth/forgot-password','POST',{email:'customer@example.com'}));
 const resetToken=new URL(sentMail.text.match(/http:\/\/[^\s]+/)[0]).searchParams.get('token');
 ok(await request('/auth/reset-password','POST',{token:resetToken,password:'ChangedTest123!'}));
 assert.equal((await request('/auth/reset-password','POST',{token:resetToken,password:'ChangedTest123!'})).status,400);
 assert.equal((await request('/auth/login','POST',{username:'testcustomer',password:'IntegrationTest123!'})).status,401);
 ok(await request('/auth/login','POST',{username:'testcustomer',password:'ChangedTest123!'}));
 console.log('PASS password reset email generation, one-time token and new password (SMTP transport simulated)');
 const catalog=ok(await request('/room-types/1'));assert.ok(Array.isArray(catalog.amenities));
 const imageForm=new FormData();imageForm.set('file',new Blob([png],{type:'image/png'}),'room.png');imageForm.set('is_primary','true');
 const imageResponse=await fetch(base+'/admin/room-types/1/images',{method:'POST',headers:{Authorization:'Bearer '+admin},body:imageForm});assert.equal(imageResponse.status,201);
 const image=(await imageResponse.json()).data;
 const [[imageRecord]]=await pool.execute('SELECT file_path FROM room_images WHERE image_id=?',[image.image_id]);fileKeys.push(imageRecord.file_path);
 assert.equal((await fetch(base+`/room-images/${image.image_id}/file`)).status,200);
 ok(await request(`/admin/room-images/${image.image_id}`,'DELETE',undefined,admin));
 console.log('PASS catalogue and public room images');
 console.log('ALL INTEGRATION CHECKS PASSED (isolated database)');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{
 if(server)await new Promise(resolve=>server.close(resolve));
 if(pool)await pool.end();
 for(const key of fileKeys)await require('../src/lib/files').remove(key);
 if(control){if(created&&/^hotel_test_[a-f0-9]{16}$/.test(dbName))await control.query('DROP DATABASE `'+dbName+'`');await control.end();}
});
