<script setup>
import { computed,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';
import { Menu,X,LogOut,ArrowUpRight,LayoutDashboard,BedDouble,DoorOpen,CalendarDays,CreditCard,FileCheck,BarChart3,Settings2,ChevronRight,Bell,ShieldCheck } from 'lucide-vue-next';
import { session,clearSession } from './lib/api';import { notices } from './lib/ui';
const route=useRoute(),router=useRouter(),open=ref(false);const admin=computed(()=>route.path.startsWith('/admin'));
const nav=[['/admin','ภาพรวม',LayoutDashboard],['/admin/room-types','ประเภทห้อง',BedDouble],['/admin/rooms','ห้องพัก',DoorOpen],['/admin/amenities','สิ่งอำนวยความสะดวก',Settings2],['/admin/bookings','การจอง',CalendarDays],['/admin/payments','การชำระเงิน',CreditCard],['/admin/documents','เอกสารยืนยัน',FileCheck],['/admin/reports','รายงาน',BarChart3]];
function logout(){clearSession();open.value=false;router.push('/login');}
</script>
<template>
<a class="skip-link" href="#main-content">ข้ามไปเนื้อหา</a>
<div v-if="admin" class="admin-shell"><aside class="sidebar" :class="{open}"><RouterLink to="/admin" class="brand"><span class="brand-mark">H</span><span>HMS HOTEL<small>MANAGEMENT WORKSPACE</small></span></RouterLink><p class="nav-caption">จัดการโรงแรม</p><nav><RouterLink v-for="[path,text,icon] in nav" :key="path" :to="path" :class="{selected:route.path===path}" @click="open=false"><component :is="icon" :size="19"/>{{ text }}<ChevronRight v-if="route.path===path" :size="15" class="nav-arrow"/></RouterLink></nav><div class="sidebar-bottom"><div class="access-label"><ShieldCheck :size="17"/> พื้นที่สำหรับผู้ดูแลระบบ</div><RouterLink to="/" class="sidebar-site">เปิดเว็บไซต์โรงแรม <ArrowUpRight :size="16"/></RouterLink><button @click="logout"><LogOut :size="16"/> ออกจากระบบ</button></div></aside><button v-if="open" class="mobile-scrim" aria-label="ปิดเมนู" @click="open=false"></button><div class="admin-main"><header class="admin-topbar"><button class="icon-btn mobile-only" aria-label="เปิดเมนู" @click="open=!open"><Menu/></button><div class="breadcrumb">Workspace <ChevronRight :size="14"/> <strong>{{ route.meta.title }}</strong></div><div class="admin-account"><span class="secure-indicator">ระบบจัดการโรงแรม</span><span class="avatar">{{ session.user?.username?.[0]?.toUpperCase() || 'A' }}</span><span>{{ session.user?.username }}<small>Administrator</small></span></div></header><main id="main-content" class="admin-content"><RouterView/></main></div></div>
<div v-else class="customer-shell"><header class="site-header"><div class="container header-inner"><RouterLink to="/" class="brand"><span class="brand-mark">H</span><span>HMS HOTEL<small>STAY A LITTLE LONGER</small></span></RouterLink><button class="icon-btn mobile-only" :aria-expanded="open" aria-label="เปิดเมนู" @click="open=!open"><X v-if="open"/><Menu v-else/></button><nav class="site-nav" :class="{open}"><RouterLink to="/" @click="open=false">หน้าหลัก</RouterLink><RouterLink to="/rooms" @click="open=false">ห้องพัก</RouterLink><RouterLink to="/contact" @click="open=false">ติดต่อเรา</RouterLink><RouterLink v-if="session.user?.role==='customer'" to="/my-bookings" @click="open=false">การจองของฉัน</RouterLink><RouterLink v-if="session.user?.role==='admin'" to="/admin" class="btn outline" @click="open=false">จัดการโรงแรม</RouterLink><template v-if="session.user"><RouterLink v-if="session.user.role==='customer'" to="/profile" class="user-chip" @click="open=false"><span class="avatar small">{{ session.user.username[0].toUpperCase() }}</span>{{ session.user.username }}</RouterLink><button class="icon-btn" aria-label="ออกจากระบบ" @click="logout"><LogOut :size="18"/></button></template><template v-else><RouterLink to="/login" @click="open=false">เข้าสู่ระบบ</RouterLink><RouterLink to="/rooms" class="btn primary" @click="open=false">จองห้องพัก <ArrowUpRight :size="16"/></RouterLink></template></nav></div></header><main id="main-content"><RouterView/></main><footer class="site-footer"><div class="container footer-main"><div><RouterLink to="/" class="brand light"><span class="brand-mark">H</span><span>HMS HOTEL<small>STAY A LITTLE LONGER</small></span></RouterLink><p>ทุกการเข้าพัก เริ่มต้นด้วยความสบายใจ<br/>เลือกห้องที่ใช่ แล้วให้เราดูแลช่วงเวลาของคุณ</p></div><div><h4>ค้นพบการพักผ่อน</h4><RouterLink to="/rooms">ห้องพักทั้งหมด</RouterLink><RouterLink to="/my-bookings">การจองของฉัน</RouterLink><RouterLink to="/contact">ติดต่อโรงแรม</RouterLink></div><div><h4>บัญชีของคุณ</h4><RouterLink to="/login">เข้าสู่ระบบ</RouterLink><RouterLink to="/register">สมัครสมาชิก</RouterLink><RouterLink to="/forgot-password">ลืมรหัสผ่าน</RouterLink></div><div class="footer-note"><ShieldCheck :size="25"/><h4>จองตรงกับโรงแรม</h4><p>ตรวจสอบรายละเอียดและติดตาม<br/>สถานะการจองได้ในบัญชีของคุณ</p></div></div><div class="container footer-bottom"><span>© {{ new Date().getFullYear() }} HMS Hotel</span><span>Hotel Management System</span></div></footer></div>
<div class="toast-stack" aria-live="polite"><div v-for="notice in notices" :key="notice.id" class="toast" :class="notice.kind">{{ notice.message }}</div></div>
</template>
