<script setup>
import { computed,reactive,ref,watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { Eye,EyeOff,ArrowRight,ShieldCheck } from 'lucide-vue-next';import { api,login } from '../lib/api';import { notify } from '../lib/ui';
const route=useRoute(),router=useRouter(),busy=ref(false),error=ref(''),success=ref(''),visible=ref(false);
const mode=computed(()=>route.path.slice(1));const titles={login:['ยินดีต้อนรับกลับ','เข้าสู่ระบบเพื่อดูแลทุกการเข้าพักของคุณ'],register:['เริ่มต้นการเข้าพักที่ดี','สร้างบัญชีเพื่อจองห้องและติดตามทุกขั้นตอน'],'forgot-password':['ลืมรหัสผ่านใช่ไหม?','เราจะส่งลิงก์ตั้งรหัสผ่านใหม่ไปยังอีเมลของคุณ'],'reset-password':['ตั้งรหัสผ่านใหม่','เลือกรหัสผ่านที่ปลอดภัยสำหรับบัญชีของคุณ']};
const form=reactive({username:'',email:'',password:'',confirm:'',first_name:'',last_name:'',phone:''});watch(mode,()=>{error.value='';success.value='';form.password='';form.confirm='';});
async function submit(){busy.value=true;error.value='';success.value='';try{
 if(['register','reset-password'].includes(mode.value)&&form.password!==form.confirm)throw Error('รหัสผ่านยืนยันไม่ตรงกัน');
 if(mode.value==='login'){const user=await login({username:form.username.trim(),password:form.password});const redirect=String(route.query.redirect||'');notify('เข้าสู่ระบบสำเร็จ');router.push(user.role==='admin'?'/admin':(/^\/(?!\/)/.test(redirect)&&!redirect.startsWith('/admin')?redirect:'/my-bookings'));}
 else if(mode.value==='register'){await api('/auth/register',{method:'POST',body:{username:form.username.trim(),email:form.email,password:form.password,first_name:form.first_name,last_name:form.last_name,phone:form.phone}});notify('สมัครสมาชิกสำเร็จ กรุณาเข้าสู่ระบบ');router.push({path:'/login',query:route.query});}
 else if(mode.value==='forgot-password'){const r=await api('/auth/forgot-password',{method:'POST',body:{email:form.email}});success.value=r.data.message;}
 else {if(!route.query.token)throw Error('ลิงก์นี้ไม่มี token กรุณาขอลิงก์ใหม่');await api('/auth/reset-password',{method:'POST',body:{token:String(route.query.token),password:form.password}});notify('เปลี่ยนรหัสผ่านแล้ว กรุณาเข้าสู่ระบบ');router.push('/login');}
}catch(e){error.value=e.details?.length?e.details.map(d=>d.message).join(' · '):e.message;}finally{busy.value=false;}}
</script>
<template><section class="auth-page"><div class="auth-visual"><img src="/hero.jpg" alt="ภาพประกอบโรงแรม"/><div><p class="eyebrow light">A LITTLE REST GOES A LONG WAY.</p><h2>พื้นที่ของคุณ<br/>สำหรับวันพักผ่อน</h2><p>เลือกห้องที่ใช่ จัดการการจอง<br/>แล้วเตรียมพร้อมสำหรับช่วงเวลาที่ดี</p><span><ShieldCheck :size="18"/> ทุกการจอง ติดตามได้ในบัญชีเดียว</span></div></div><div class="auth-form-wrap"><div class="auth-form"><p class="eyebrow">HMS HOTEL</p><h1>{{ titles[mode]?.[0] }}</h1><p class="muted">{{ titles[mode]?.[1] }}</p><div v-if="error" class="alert danger" role="alert">{{ error }}</div><div v-if="success" class="alert success" role="status">{{ success }}</div><form @submit.prevent="submit"><div v-if="mode==='register'" class="form-grid"><label>ชื่อ<input v-model="form.first_name" required maxlength="100" autocomplete="given-name"/></label><label>นามสกุล<input v-model="form.last_name" required maxlength="100" autocomplete="family-name"/></label></div><label v-if="['login','register'].includes(mode)">ชื่อผู้ใช้<input v-model="form.username" required :minlength="mode==='register'?3:1" maxlength="50" autocomplete="username" placeholder="ชื่อผู้ใช้ของคุณ"/></label><label v-if="['register','forgot-password'].includes(mode)">อีเมล<input v-model="form.email" type="email" required maxlength="150" autocomplete="email" placeholder="you@example.com"/></label><label v-if="mode==='register'">เบอร์โทรศัพท์<input v-model="form.phone" type="tel" required maxlength="20" autocomplete="tel" placeholder="08x xxx xxxx"/></label><label v-if="mode!=='forgot-password'">รหัสผ่าน<div class="password-field"><input v-model="form.password" :type="visible?'text':'password'" required :minlength="mode==='login'?1:8" :autocomplete="mode==='login'?'current-password':'new-password'" placeholder="กรอกรหัสผ่าน"/><button type="button" class="icon-btn" :aria-label="visible?'ซ่อนรหัสผ่าน':'แสดงรหัสผ่าน'" @click="visible=!visible"><EyeOff v-if="visible" :size="18"/><Eye v-else :size="18"/></button></div></label><p v-if="['register','reset-password'].includes(mode)" class="field-help">อย่างน้อย 8 ตัว มีตัวเล็ก ตัวใหญ่ ตัวเลข และอักขระพิเศษ</p><label v-if="['register','reset-password'].includes(mode)">ยืนยันรหัสผ่าน<input v-model="form.confirm" type="password" required minlength="8" autocomplete="new-password"/></label><RouterLink v-if="mode==='login'" to="/forgot-password" class="forgot-link">ลืมรหัสผ่าน?</RouterLink><button class="btn primary full" :disabled="busy">{{ busy?'กำลังดำเนินการ…':mode==='login'?'เข้าสู่ระบบ':mode==='register'?'สร้างบัญชี':mode==='forgot-password'?'ส่งลิงก์ตั้งรหัสผ่าน':'บันทึกรหัสผ่านใหม่' }}<ArrowRight v-if="!busy" :size="18"/></button></form><p class="auth-bottom" v-if="mode==='login'">ยังไม่มีบัญชี? <RouterLink :to="{path:'/register',query:route.query}">สมัครสมาชิก</RouterLink></p><p class="auth-bottom" v-else><RouterLink :to="{path:'/login',query:route.query}">กลับไปเข้าสู่ระบบ</RouterLink></p></div></div></section></template>
